spring:
  application:
    name: auth
  security:
    oauth2:
      authorizationserver:
        client:
          default-client:
            token:
              access-token-time-to-live: 1h
            registration:
              client-id: "default-client"
              client-secret: "{noop}default-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/authorize/oauth2/code/authserver"
                - "http://localhost:8080/authorize/oauth2/code/authserver"
                - "https://adoptions-assistant.apps.tas-ndc.kuhn-labs.com/authorize/oauth2/code/authserver"

server:
  port: 9000
  servlet:
    session:
      cookie:
        name: MCP_AUTHORIZATION_SERVER_SESSIONID
